### ISSUE TITLE
Add cmake check for timegm

### ISSUE THREAD

**Issue by szekerest** [mapserver/mapcache#112]
MSVC doesn't support this function by default

in cmake we should add:

check_function_exists ("timegm"  HAVE_TIMEGM)

in the code:
# ifndef HAVE_TIMEGM

time_t timegm(struct tm *tm)
{
  time_t t, tdiff;
  struct tm in, gtime, ltime;

  memcpy(&in, tm, sizeof(in));
  t = mktime(&in);

  memcpy(&gtime, gmtime(&t), sizeof(gtime));
  memcpy(&ltime, localtime(&t), sizeof(ltime));
  gtime.tm_isdst = ltime.tm_isdst;
  tdiff = t - mktime(&gtime);

  memcpy(&in, tm, sizeof(in));
  return mktime(&in) + tdiff;
}
# endif

**Comment by jmckenna** [comment]
@szekerest this is the same point I was trying to make back in January 2014 (http://osgeo-org.1560.x6.nabble.com/MapCache-use-of-timegm-on-Windows-td5098696.html).  Was your solution applied to master?

**Comment by szekerest** [comment]
@jmckenna it hasn't yet been added as far as I see
