### ISSUE TITLE
Values for Min/MaxTileRow/Col in TilematrixLimits sections of GetCapabilities

### ISSUE THREAD

**Issue by rillat** [mapserver/mapcache#117]
Hi,

There are two things wrong with the values used in the TilematrixLimits sections of the WMTS GetCapabilities. The TileCol-values and TileRow-values have been switched and for the TileRow-values the upperleft-origin hasn't been taken into account.

For example:

TileMatrixLimits
TileMatrix GoogleMaps:9
MinTileRow 254
MaxTileRow 269
MinTileCol 334
MaxTileCol 346

Should be:

TileMatrixLimits
TileMatrix GoogleMaps:9
MinTileRow 165 [(Max nr of tiles: 512) -1) - 346]
MaxTileRow 177 [(Max nr of tiles: 512) -1) - 334]
MinTileCol 254
MaxTileCol 269

Regards,

Stijn

**Comment by tbonfort** [comment]
When you say that the upperleft-origin hasn't been taken into account, do you mean when the grid has been configured with ```origin="top-left"``` or all the time ?
