### ISSUE TITLE
mapcache-config.h not found

### ISSUE THREAD

**Issue by drtzack** [mapserver/mapcache#122]
nmake /F Makefile.vc throws error on windows 7.

C:\Users\Zack\Desktop\geolocation\mapcache-master\include\mapcache.h(37) : fatal
 error C1083: Cannot open include file: 'mapcache-config.h': No such file or dir
ectory
NMAKE : fatal error U1077: '"C:\Users\Zack\AppData\Local\Programs\Common\Microso
ft\Visual C++ for Python\9.0\VC\Bin\cl.EXE"' : return code '0x2'
Stop.

**Comment by tbonfort** [comment]
mapcache builds with cmake. the nmake files included in the archive are historical and unused now.
