### ISSUE TITLE
Mapcache problem with reverse axis projection

### ISSUE THREAD

**Issue by tudorbarascu** [mapserver/mapcache#123]
Hi,

EPSG:3844, the Romania projection is one of the projections with N-E axis order.
For the local extent that I'm using,
                 minlon, minlat,  ....
``<extent>388512,332495,464441,454917</extent>``,
mapcache outputs an incorrect Top Left corner of the computed matrixes,
and that is:

``<TopLeftCorner>475855.000000 388512.000000</TopLeftCorner>``
instead of the correct one:
``<TopLeftCorner>388512.0 454917.0</TopLeftCorner>``  (minLon,maxLat).

Is there a way in mapcache to say that it's a reverse (yx) axis projection?
The source is a 1.3.0 WMS server (Qgis).
Thank you,
Tudor

**Comment by tbonfort** [comment]
If I understand correctly, the TopLeftCorner should be given in the order defined by the CRS, so mapcache is doing the right thing by giving you those in y,x order rather than x,y one. Grids in mapcache are always defined with the bottom left corner being the reference point (unless you use the grid-origin modifier), and so the value for "y" in the TopLeftCorner of a given TileMatrix is dependent on the ScaleDenominator and may not exactly match the given maxy of your provided mapcache extent, thus the difference between 475855 and 454917.
For me there's no bug to be found here, please re-open if not.

**Comment by tudorbarascu** [comment]
Thanks for taking a look Thomas. From my understanding:

```
   <grid name="grid_2008">
    ....
      <extent>332495,388512,454917,464441</extent>
      <srs>EPSG:3844</srs>
      <resolutions>280 112 56 28 14 5.6 2.8 1.4 0.56 0.28</resolutions>
      <units>m</units>
      <size>256 256</size>
      <origin>top-left</origin>
   </grid>
```
I configured the extent above using ``minLat, minLon, maxLat, maxLon`` as the projection has reverse axis.

The response for TopLeft corner should be ``minLat, maxLon`` but I get ``maxLon, minLat`` or ``<TopLeftCorner>464441.000000 332495.000000</TopLeftCorner>``

Am I wrong in my expectations?

**Comment by tbonfort** [comment]
mapcache expects all of its extents to me in lonlat, and does the translation to latlon if needed at request time, i.e. your <extent> should be minlon,minlat,maxlon,maxlat

**Comment by tudorbarascu** [comment]
I had tried that in the beginning:
```
   <grid name="vl_full_1.1.1">
      <metadata>
         <title>Valcea 3844 lon lat</title>
      </metadata>
      <extent>388512,332495,464441,454917</extent>
      <srs>EPSG:3844</srs>
      <resolutions>280 112 56 28 14 5.6 2.8 1.4 0.56 0.28 0.14 0.07 0.028 0.014 0.007</resolutions>
      <units>m</units>
      <size>256 256</size>
      <origin>top-left</origin>
   </grid>
```
With the extent given above in minLon, minLat.., as mapcache expects, I get the following output:

* Response from WMS capabilities:
```
<BoundingBox SRS="EPSG:3844" minx="388512.000000" miny="332495.000000" maxx="464441.000000" maxy="454917.000000"/>
```
 The BBOX should be minx,miny,maxx,maxy in units of the SRS, which for my case is `minLat,minLon...`) but I get `minLon,minLat...`.

* From WMTS capabilities response `<TopLeftCorner>454917.000000 388512.000000</TopLeftCorner>`
  Top left should be for my case `minLat, maxLon` but I get `maxLat, minLon` as you can see.

Do you think I have false expectations?
Thank you

PS. I made a pull request to update the docs, https://github.com/mapserver/docs/pull/129

**Comment by tbonfort** [comment]
- For the WMS capabilities, mapcache only outputs 1.1.1 wms, so there is no need to switch the x and y values in the BoundingBox
- For the WMTS part, why are you expecting MinLat,MaxLon? The TopLeftCorner point is immutable (minlon,maxlat) and doesn't depend on the grid origin or the axis orientation, and here MapCache is effectively returning it in lat,lon order as is mandated by your crs's axis orientation

**Comment by tudorbarascu** [comment]
You're right for WMS, I got bamboozled.
For the WMTS, I looked into the standard http://portal.opengeospatial.org/files/?artifact_id=35326 and it's written there that the TopLeftCorner is `Position in CRS coordinates of the top-left corner of this tile
matrix`. As my first axis is North, shouldn't I expect latitude and then longitude?

I couldn't find anywhere that the top left corner is always given in `Lon, Lat`, and not in `Lat, Lon`.
I may be wrong. 
However, I tried connecting with Openlayers, QGIS and other WMTS clients and I couldn't get mapcache to work regardless on how I configured it.
I had no problems using other projections etc.

**Comment by tbonfort** [comment]
From what I understand, the top-left corner in mapcache terms is *always* the (minx,maxy) point. It is returned to the client as minx,maxy or maxy,minx depending on the axis ordering dictated by the CRS.
I'm not saying there's nothing to fix in mapcache, but for the time being my understanding is that mapcache is doing the correct thing here.

``` Top left should be for my case minLat, maxLon``` => that's the bottom-right corner

I'm not sure you're getting the meaning of mapcache's "origin" modifier: it only applies to the alignment of the stored tiles, and comes into effect when your choice of resolutions does not align to the extent of your grid (i.e. not for WGS84 and googlemapscompatible grids which use power-of-two resolutions), see for example https://lists.osgeo.org/pipermail/mapserver-users/2014-October/077061.html

**Comment by tudorbarascu** [comment]
Yes, I realized my false assumption about the grid.
I'm just saying that the coordinates in a reverse axes projection should be given in (North, East) succession, so Latitude then Longitude.

**Comment by tbonfort** [comment]
you're getting ```<TopLeftCorner>454917.000000 388512.000000</TopLeftCorner>``` which is lat,lon of the topleftcorner. where's the issue?

**Comment by tudorbarascu** [comment]
It's in my logic as I have gone astray trying to find why the clients don't work.
Thanks a lot Thomas! Sorry for the bugging.
