### ISSUE TITLE
Proxy requests outside a tileset's minzoom/maxzoom range to MapServer?

### ISSUE THREAD

**Issue by p-madden** [mapserver/mapcache#132]
It would be useful (to me, at least) to have an option to request proxying of requests outside a tileset's minzoom/maxzoom range to the underlying MapServer WMS service. In our application, for example, deep zoom levels are expensive to cache, but are served quickly enough by MapServer that we don't mind not caching them. Our application allows zoom levels 1 - 14 but, if I set minzoom="1" /  maxzoom="12" on &lt;grid&gt; for my &lt;tileset&gt;, levels 13 and 14 simply will not be rendered, even if I configure a &lt;forwarding_rule&gt; for the layer in question. It would be nice if requests at levels 13 and 14, in this case, could simply pass through to MapServer.

Please consider this an enhancement request.

**Comment by tbonfort** [comment]
possible, but will require funding.

**Comment by maddenp** [comment]
Understood. For now, the alternative (not seeding the deep levels, but allowing MapCache to cache them on demand) is workable. Please feel free to close this -- I could revisit it if the need became more acute and funding were available.
