### ISSUE TITLE
Disable propagation of tiles between tier multicaches? 

### ISSUE THREAD

**Issue by p-madden** [mapserver/mapcache#133]
I'm not sure how concerned I need to be about concurrent writes to sqlite3 cache backends, but I have been considering using using a multitier cache to avoid risk. My thought was to configure something like
```
<cache name="multitier" type="multitier">
  <cache>db1</cache>
  <cache>db2</cache>
</cache>
```
with `db1` and `db2` as sqlite3 caches, and then to run a single-threaded mapcache_seed on `db1`. Until `db1` is fully seeded, user requests would pass through to `db2`, which would make WMS requests to MapServer as needed. Once `db1` was fully seeded, `db2` would no longer be used. But I read in the MapCache documentation:

> If a given tile isn’t found in the first child cache, it will be read from the second child cache and copied into the first child cache for subsequent accesses.

The "and copied" implies, to me, that `db1` will be subject to concurrent writes, which was what I was trying to avoid.

As an enhancement, might it be possible -- if it is a useful idea, I'm not actually sure -- to add an option to disable the "and copied" behavior? If I understand, this would allow one to avoid concurrent writes completely.

**Comment by tbonfort** [comment]
The intent of the multitier cache is to mix fast/small/expensive caches (the first one) with slow/large/cheap ones (the second one). It would be possible to add a cache backend that does what you need but it will need some development (start from the fallback or multitier cache if you want to provide a patch, or contract me to do it for you). This is sort of an edge case, if I were you I'd seed with one configuration file (or use the --cache option of mapcache_seed) , and then gracefully restart your server instance to use the newly populated db file once the seeding is over.

**Comment by maddenp** [comment]
If my own funding permits it, I'll see if I can provide a patch. And thank you for the good ideas about swapping cache files and mapcache_seed --cache (I wasn't aware of this switch). Please feel free to close this, of course.
