### ISSUE TITLE
Mapcache_seeder: Auto seed all grids in a tileset

### ISSUE THREAD

**Issue by rastermanden** [mapserver/mapcache#136]
I have a tileset with a growing number of grids in different projections.
I have an ogr datasource with the invalidation geometries in epsg:4326
I need the best way to handle the invalidation of the cache

Currently I run mapcache_Seeder once for each grid in a tileset and use a reprojected datasource corresponding to the projection in the grid

I would like this to be handled by the mapcache_seeder tool. The documentation states:
>Important: Note that, for the time being, the OGR datasource should be in the same projection as the grid you are seeding, as there is no automatic reprojection from the datasource projection to the grid projection. 

I read "for the time beeing" as this feature might be implemented in the future :). Is this the case ? 

If this is going to be implemented, I suggest that the -g flag would take a list of grid names and/or an "all grids" value and then MapCache would do the necessary reprojection of the ogr datasource.

**Comment by tbonfort** [comment]
The list of grids or "all grids" feature is very low priority for now given how the seeder is architectured. The reprojection part needs someone to provide a patch or some funding as it doesn't scratch one of my itches :). If you name your grids by their epsg code you can script this rather easily:
```bash
for grid in 4326 3857 12345; do
  ogr2ogr -t_srs epsg:$grid  out_$grid.shp in.shp
  mapcache_seed  .... -g $grid -d out_$grid.shp
end
```
