### ISSUE TITLE
error while compiling mod_mapcache.so

### ISSUE THREAD

**Issue by geomartino** [mapserver/mapcache#138]
Hi,

I'm on centos6 (64bits) and when and compiling mapcache (cmake .. -DWITH_SQLITE=0 -DWITH_APACHE=1 -DWITH_FCGI=0), the process is stopped at the end with this message:

Scanning dependencies of target mod_mapcache
[100%] Building C object apache/CMakeFiles/mod_mapcache.dir/mod_mapcache.c.o
/usr/local/src/mapcache/apache/mod_mapcache.c: In function ‘mapcache_add_alias’:
/usr/local/src/mapcache/apache/mod_mapcache.c:637: error: ‘NOT_IN_HTACCESS’ undeclared (first use in this function)
/usr/local/src/mapcache/apache/mod_mapcache.c:637: error: (Each undeclared identifier is reported only once
/usr/local/src/mapcache/apache/mod_mapcache.c:637: error: for each function it appears in.)
make[2]: *** [apache/CMakeFiles/mod_mapcache.dir/mod_mapcache.c.o] Error 1
make[1]: *** [apache/CMakeFiles/mod_mapcache.dir/all] Error 2
make: *** [all] Error 2

any thoughts?

If this issue tracker is not the right place to ask the question, please provide me the official url or mailing list so I can submit it to the community.

best regards,

MartinO

**Comment by tbonfort** [comment]
@geomartino , this was fixed in 93fef0d

**Comment by geomartino** [comment]
thank you very much Thomas, problem solved!

MartinO
