### ISSUE TITLE
Tiles reprojection and white lines (holes) between tiles

### ISSUE THREAD

**Issue by geoek** [mapserver/mapcache#146]
I try to generate tiles of an area.

I have allready a set of tiles with projection 2154 (only one zoom level). They are served by mapserver thanks to a mapfile that address an index file (projection 2154) with the references of my tiles.

Now, i want to generate a set of tiles (pyramid) in another projection : 3943.
In my mapfile, i have add the output projection (3943).
I have write the xml file for the configuration of mapcache, with a grid of my new projection (3943).

When i test, everything is ok but i have sometimes white lines between tiles due to holes. I think it is because of the reprojection. The new tiles are not corectly aligned.

What can i do to solve this problem ?

Thanks in advance.

**Comment by tbonfort** [comment]
can you try the patch in mapserver/mapserver#1715 and report back please

**Comment by geoek** [comment]
Thanks tbonfort !

But i forgot to add my configuration : MS4W 3.1.3 - MapServer/Mapscript 7.0.1 - MapCache 1.4.1
I think the bug has been corrected since then... 

And I'm not sure how i must proceed. I think it will be a better solution to reproject all my initial tiles, create a new index in my new projection, and then generate my set of tiles.

What do you think ?

**Comment by tbonfort** [comment]
you can try that, but there's no guarantee it'll solve the problem, #1715 also concerns un-reprojected data for some people.
