### ISSUE TITLE
Source WMS max size for getMap request

### ISSUE THREAD

**Issue by t1geomatika** [mapserver/mapcache#147]
Hi,

I'm trying to use a WMS via a local mapcache instance.
This WMS allow only request with size between 100x100 and 1280x1024.
It works for the low zoom level but after there are errors : image size too big.

Because height = 1300 and is > max height for this service (1024)

( GET /scpc/64102.wms?VERSION=1.3.0&REQUEST=GetMap&SERVICE=WMS&STYLES=&BBOX=340043.725968%2c6271489.434555%2c342823.614857%2c6276075.545666&WIDTH=788&HEIGHT=1300&FORMAT=image%2fpng&SRS=EPSG%3a2154&DPI=96&FORMAT_OPTIONS=dpi%3a96&MAP_RESOLUTION=96&CRS=epsg%3a2154&TRANSPARENT=true&MAP=64102&LAYERS=HYDRO)

Is it possible to configure mapcache to use a max size when calling WMS source?

Thanks in advance.

**Comment by tbonfort** [comment]
Unfortunately it is not possible.
