### ISSUE TITLE
mapcache_seed hang on error

### ISSUE THREAD

**Issue by juliensam** [mapserver/mapcache#154]
When there's an error during the seeding the process never terminate. We have to Ctrl+c it to stop the process.

Hints:
- Since 19553ebf02a86b593137e17dc38d387ea9ac1220 the error detection in mapcache_seed.c at line 777 do not return anymore so it may stay in the while loop forever. So maybe `while(!error_detected)` would do the trick.
- Should we make the `error_detected` variable volatile so it's shared between thread?

If you agree on the solution, I can provide a Pull Request.

**Comment by tbonfort** [comment]
I have that fixed in a branch that needs merging. For now you can just add a ```return NULL``` after ```error_detected=1```

**Comment by tbonfort** [comment]
@juliensam sorry, forget my previous comment. What version/commit of mapcache are you using?

**Comment by juliensam** [comment]
I'm using 1.4.1 right now, but I'm fairly sure that I tested with master as well.

**Comment by tbonfort** [comment]
are you sure about master. it was supposed to be fixed in e1083e3af94ff093bf17517b  (killing the logging thread made the seeding threads hang while waiting for slots in the logging queue to free up, which never happened)

**Comment by juliensam** [comment]
I'll retry with master and report back

**Comment by juliensam** [comment]
master is working! e1083e3 indeed fixed the issue.
