### ISSUE TITLE
Blurry tiles using GetMap requests on mapcache

### ISSUE THREAD

**Issue by sgrossberndt** [mapserver/mapcache#157]
When requesting tiles via the `<service type="wms">` these are blurred when using `<resample_mode>bilinear</resample_mode>` or have artifacts on labels when using `<resample_mode>nearest</resample_mode>` while the original mapserv requests are not blurry - neither are the cached tiles in `/tmp/nrw-touristisch/nrw/*`.

Image returned by mapserv without caching is fine: 
![mapserv](https://cloud.githubusercontent.com/assets/3786510/22289688/3cfda232-e2fd-11e6-9d57-9f1e4d5f1a21.png)
`/mapserv?FORMAT=image/png&LAYERS=MS&REQUEST=GetMap&SERVICE=WMS&SRS=EPSG:31466&VERSION=1.1.1&map=my.map&BBOX=2586000,5650000,2602000,5666000&WIDTH=256&HEIGHT=256`

Image returned by Mapcache when using `<resample_mode>bilinear</resample_mode>` is blurred:
![mapcache_bilinear](https://cloud.githubusercontent.com/assets/3786510/22289689/3d015ab2-e2fd-11e6-977c-f2be6bd86e5d.png)
`/mapcache?FORMAT=image/png&LAYERS=nrw-touristisch&REQUEST=GetMap&SERVICE=WMS&SRS=EPSG:31466&VERSION=1.1.1&BBOX=2586000,5650000,2602000,5666000&WIDTH=256&HEIGHT=256`

Image returned by Mapcache when using `<resample_mode>nearest</resample_mode>` has artifacts on labels:
![mapcache_nearest](https://cloud.githubusercontent.com/assets/3786510/22289690/3d03042a-e2fd-11e6-9b51-84790d57abe2.png)

Any ideas what is wrong here?

This is my `mapcache.xml`:
```<?xml version="1.0" encoding="UTF-8"?>
<mapcache>
    <grid name="nrw">
        <metadata>
            <title>NRW</title>
        </metadata>
        <extent>2490000 5570000 2746000 5826000</extent>
        <srs>EPSG:31466</srs>
        <units>m</units>
        <size>256 256</size>
        <resolutions>4096 2048 1024 512 256 128 64 32 16 8 4 2 1 0.5 0.25 0.125 0.0625</resolutions>
    </grid>
    <source name="touristisch" type="wms">
        <getmap>
            <params>
                <FORMAT>image/png</FORMAT>
                <LAYERS>MS</LAYERS>
                <MAP>my.map</MAP>
            </params>
        </getmap>
        <http>
            <url>http://127.0.0.1/mapserv</url>
        </http>
    </source>
    <format name="PNG_BEST" type="PNG">
        <compression>best</compression>
    </format>
    <default_format>PNG_BEST</default_format>
    <cache name="disk" type="disk">
        <base>/tmp</base>
        <symlink_blank/>
    </cache>
    <tileset name="nrw-touristisch">
        <source>touristisch</source>
        <cache>disk</cache>
        <grid use_wms_intermediate_resolutions="true">nrw</grid>
        <format>PNG_BEST</format>
        <metatile>2 2</metatile>
        <metabuffer>5</metabuffer>
        <expires>60</expires>
    </tileset>
    <service type="wms" enabled="true">
        <full_wms>error</full_wms>
        <resample_mode>bilinear</resample_mode>
        <format>PNG_BEST</format>
        <maxsize>256</maxsize>
    </service>
    <errors>report</errors>
    <locker type="disk">
        <directory>/tmp</directory>
        <timeout>300</timeout>
    </locker>
</mapcache>

**Comment by tbonfort** [comment]
not a bug. unless your WMS request's resolution exactly matches one of your grid resolutions, then resampling has to happen, which leads to some kind of visible deterioration of the rendered image

**Comment by sgrossberndt** [comment]
Thanks for pointing to the correct location: the resolutions did not match.
