### ISSUE TITLE
extract tiles from an existing cache to another in transfer mode failed 

### ISSUE THREAD

**Issue by asswclw** [mapserver/mapcache#158]
hi,
i have the same needs with this : https://trac.osgeo.org/mapserver/ticket/4075, 
but when i try mapcache_seed command in transfer mode:

mapcache_seed -c /var/www/mapcache/mapcache.xml -m transfer -x driverschool_mars_transfer -t driverschool_mars -g g_hd  -z 16,20 -e 12650479.621736677,4135412.984691071,12650541.903720174,4135490.3122502225

if the tiles in the bounding box don't exists in the source cache , then mapcache_seed doesn't create   new tiles  and copy to the extract cache specified as i think. I check the code on the github 
https://github.com/mapserver/mapcache/blob/master/util/mapcache_seed.c

I find it just returns MAPCACHE_CMD_SKIP  if the tile does not exist in transfer mode from line 442.

Anyone can give me some suggestions?
thx :)

**Comment by tbonfort** [comment]
this is not a support forum but an issue tracker. use the mailing lists...
