### ISSUE TITLE
In WMS 1.1.1 only SRSs common to all layers shall be listed in root layer

### ISSUE THREAD

**Issue by Schpidi** [mapserver/mapcache#176]
From http://portal.opengeospatial.org/files/?artifact_id=1081&version=1&format=pdf
> The root <Layer> element **shall** include a sequence of zero or more SRS elements listing _all_ SRSes that are common to all subsidiary layers. Use a single SRS element with empty content (like so: "<SRS></SRS>") if there is no common SRS.

Right now any SRS used in any defined grid is included.

**Comment by jbo-ads** [comment]
Pull request #187 aims at addressing this issue.

**Comment by tbonfort** [comment]
fixed in #187 and dca7999
