### ISSUE TITLE
502 Bad Gateway | " http://10.10.21.201/mapcache/tms/1.0.0/test@WGS84/5/35/25.png"

### ISSUE THREAD

**Issue by mixap** [mapserver/mapcache#198]
apache log : 

 Command line: '/usr/sbin/apache2'
[Mon Apr 08 15:31:42.588359 2019] [mpm_event:notice] [pid 3470:tid 140407338277824] AH00491: caught SIGTERM, shutting down
[Mon Apr 08 15:31:42.716414 2019] [mpm_event:notice] [pid 3599:tid 140418334854080] AH00489: Apache/2.4.29 (Ubuntu) mod-mapcache/1.7dev configured -- resuming normal operations
[Mon Apr 08 15:31:42.716500 2019] [core:notice] [pid 3599:tid 140418334854080] AH00094: Command line: '/usr/sbin/apache2'

mapcache.mxl

<mapcache>
   <cache name="disk" type="disk">
      <base>/tmp</base>
      <symlink_blank/>
   </cache>

   <source name="vmap0" type="wms">
      <getmap>
         <params>
          <FORMAT>image/png</FORMAT>
          <LAYERS>basic</LAYERS>
         </params>
      </getmap>
      <http>
              <url>https://foo.s3.amazonaws.com/tiles/{tileset}/{grid}/{z}/{x}/{y}/{ext}</url>

      </http>
   </source>

  <tileset name="test">
      <source>vmap0</source>
      <cache>disk</cache>
      <grid>WGS84</grid>
      <grid>g</grid>
      <size>256 256</size>
      <format>PNG</format>
      <metatile>5 5</metatile>
      <metabuffer>10</metabuffer>
      <expires>3600</expires>
   </tileset>

   <service type="tms" enabled="true">
<full_wms>assemble</full_wms>
      <resample_mode>bilinear</resample_mode>
   </service>
   <service type="wmts" enabled="true"/>
   <service type="tms" enabled="true"/>
   <service type="kml" enabled="true"/>
   <service type="gmaps" enabled="true"/>
   <service type="ve" enabled="true"/>
   <service type="mapguide" enabled="true"/>
   <service type="demo" enabled="true"/>

   <errors>report</errors>
   <lock_dir>/tmp</lock_dir>

</mapcache>
                           
Please help me and give a format for tms .!

**Comment by sdlime** [comment]
@mixap, this is really a question for the mapserver mailing lists https://mapserver.org/community/lists.html. Please post there - many more folks may be able to answer! --Steve
