### ISSUE TITLE
Expire tiles and update new after Postgres DB update using mapcache

### ISSUE THREAD

**Issue by parsispresswala** [mapserver/mapcache#204]
Hello,
It is not an issue nut a question. I have asked same on mapserver user list.
I have configure the mapserver and generated tiles using mapcahing(mapcache_seed) for whole world till 200 m scaling (zoom level 16). Now I want to update the database using changeset provided by OSM and regenerate only those tiles which data is updated in database. How should I achieve this?
I want to configure this process automatically. As some new chnages updated in database, old tiles shoud expire and new tiles should be generated itself.

**Comment by jmckenna** [comment]
Please use the MapServer-users lists for your questions.   Github is used for issues related to the software.  However, if ever you need assistance with your questions and you prefer faster support than the MapServer-users list you can at any time leverage a professional service provider listed at https://mapserver.org/community/service_providers.html

You might also consider re-sending your question to the MapServer-users list, as sometimes the community needs reminders :)

I hope that explains the process more clearly.
