### ISSUE TITLE
Berkeley DB - BDB0058 illegal page type or format

### ISSUE THREAD

**Issue by asteinereurofunk** [mapserver/mapcache#226]
Hello, I have a problem when seeding into a Berkeley DB Cache: 
The following error occours: 

**seeded 960 tiles, now at z18 x1032 y68
BDB0058 page 696120: illegal page type or format
BDB0061 PANIC: Invalid argument
BDB0060 PANIC: fatal region error detected; run recovery
BDB1581 File handles still open at environment close
BDB1582 Open file handle: /tmp/mapcache/OSM/__db.001
BDB1582 Open file handle: /tmp/mapcache/OSM/__db.002
BDB1582 Open file handle: /tmp/mapcache/OSM/__db.003
BDB1582 Open file handle: /tmp/mapcache/OSM/OSM.db
BDB0060 PANIC: fatal region error detected; run recovery
BDB0060 PANIC: fatal region error detected; run recovery
BDB0060 PANIC: fatal region error detected; run recovery
BDB1581 File handles still open at environment close
BDB1582 Open file handle: /tmp/mapcache/OSM/__db.001
BDB1582 Open file handle: /tmp/mapcache/OSM/__db.002
BDB1582 Open file handle: /tmp/mapcache/OSM/__db.003
BDB1582 Open file handle: /tmp/mapcache/OSM/OSM.db
BDB0060 PANIC: fatal region error detected; run recovery
failed to seed tile z18,x1020,y68:
dbd backend failed on tile_multiset: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery**

After I stopped the seeding process I deleted the temp files (__db.00x). Then I watched the WMS source with QGIS. When I look at a not seeded tile, mapcache is seeding it successfully and the cache is getting bigger. 
Then start the seeding process again and after some tiles the error : **BDB0058 page 696120: illegal page type or format** occurs again. Restarting Mapcache doesnt help. 

Mapcache Version 1.8.0

**Comment by asteinereurofunk** [comment]
Does someone have this problem too? I seed OSM tiles POSTGRESDB --> MAPPROXY --> MAPCACHE

**Comment by jmckenna** [comment]
@asteinereurofunk I have not hit your exact error, but I once saw a case where a "page size' limit was hit (maybe 2TB), for either BerkeleyDB or SQLite.   I just wanted to mention that here, just in case it is related.
