### ISSUE TITLE
TIME dimension example list_query produces invalid demo service

### ISSUE THREAD

**Issue by djhoese** [mapserver/mapcache#228]
The documentation for [time dimension](https://mapserver.org/mapcache/dimensions.html) handing has an example for how the time dimension should be configured. It has:

```
<!-- "time" dimension

     This example defines a "time" dimension whose possible values
     are stored in the /path/to/mapcache-time.sqlite SQLite file. The
     default value is "2010".

     A WMS request with that dimension may contain, e.g.  "...
     &time=1999-08-11T11:03:07Z/2001-09-21T08:17:56Z& ..."
-->
<dimension type="time" name="time" default="2010">
    <dbfile>/path/to/mapcache-time.sqlite</dbfile>
    <validate_query>
         SELECT strftime("%Y-%m-%dT%H:%M:%SZ",ts) FROM time
          WHERE ts &gt;= datetime(:start_timestamp,"unixepoch")
            AND ts &lt;= datetime(:end_timestamp,"unixepoch")
       ORDER BY ts DESC
    </validate_query>
    <list_query>SELECT ts FROM time</list_query>
</dimension>
```

If you use this in your config file and then go to the demo URL (`http://localhost:8889/mapcache/demo/wmts`), you can have invalid requests because the time from the `list_query` is not formatted properly. I think the `list_query` should actually be:

```
 <list_query>SELECT strftime("%Y-%m-%dT%H:%M:%SZ",ts) FROM time</list_query>
```

I'm not a SQL expert nor a MapCache expert, but this got this working for me with a SQLite database created from Python using Python's datetime objects. Since I'm not an expert I'm creating this issue instead of a PR. If this seems reasonable I can make a PR.

**Comment by jbo-ads** [comment]
This makes sense. I'll wait for your PR.
