### ISSUE TITLE
:tileset substitution not working in time dimension query

### ISSUE THREAD

**Issue by djhoese** [mapserver/mapcache#232]
I have the following time dimension defined in my XML file:

```
        <dimension type="time" name="time" default="DEFAULT">
           <dbfile>/data/mapcache_time.sqlite</dbfile>
               <validate_query>
                     SELECT strftime("%Y-%m-%dT%H:%M:%SZ",ts) FROM :tileset
                      WHERE ts &gt;= datetime(:start_timestamp,"unixepoch")
                        AND ts &lt;= datetime(:end_timestamp,"unixepoch")
                   ORDER BY ts DESC
                </validate_query>
                ...
        </dimension>
```

where based on the documentation I expected the `:tileset` to be replaced with the name of the tileset (which I also used as the name of the table in the database). However, when requesting a tile and when the query actually runs it says the `:tileset` table isn't defined (or something like that). Am I doing this wrong or misunderstanding the documentation?

Side question: Is it possible to use environment variables or some other method for replacing parameters in the XML file? For example a `source`'s HTTP URL. This would be helpful for testing versus operational use where, assuming I'm running from a docker image, I can easily switch what source URL is being used by setting an environment variable.

**Comment by jbo-ads** [comment]
This is indeed a SQLite3 feature. SQL parameters can only be used for binding literal values, not database identifiers like tables or columns.

This is not clearly documented, see [Chapter 6 of "An Introduction To The SQLite C/C++ Interface"](https://www.sqlite.org/cintro.html#binding_parameters_and_reusing_prepared_statements):

>  (Parameters may not be used for column or table names.)

Side answer: No it is not possible. The environment variable should belong to Apache executable environment and would not be taken into account while Apache is running. A workaround is to define as many MapCache configuration files as needed `source`'s HTTP URL.

**Comment by djhoese** [comment]
Ah ok, makes sense. Thanks.

As for environment variables I ended up going with a startup script that uses sed to replace the parts of the XML that need it and then starts Apache. Seems to be good enough for now.
