### ISSUE TITLE
missing parameter of the mapcache_seed feature in the documentation

### ISSUE THREAD

**Issue by asteinereurofunk** [mapserver/mapcache#236]
hello, 

in this documentation [https://mapserver.org/mapcache/seed.html](https://mapserver.org/mapcache/seed.html) some commandline options are missing. 

e.g. 

- -P, --precent number

Percent of failed requests allowed from the last 1000 before we abort (default: 1%, set to 0 to abort on first error).

- -L, --log-failed file

Log failed tiles to file.

- -R, --retry-failed file

Rtry failed req

all commandline options are in here --> [https://manpages.debian.org/unstable/mapcache-tools/mapcache_seed.1.en.html](https://manpages.debian.org/unstable/mapcache-tools/mapcache_seed.1.en.html)

could you add this to the official documentation at mapserver.org?

**Comment by jmckenna** [comment]
@asteinereurofunk could you create a Pull Request of your changes to https://github.com/mapserver/docs into branch-7-6 ?

**Comment by asteinereurofunk** [comment]
#done --> [https://github.com/mapserver/docs/pull/326](https://github.com/mapserver/docs/pull/326)
