### ISSUE TITLE
MapCache compress tiles on every request

### ISSUE THREAD

**Issue by jezza12111** [mapserver/mapcache#237]
MapCache use compression (if set) on every request which causes high cpu load if we have many request. Why can't store compressed tile? If i requested the tile, i get the tile immediately without additional cpu usage. With this behavior can I reach more req/s. Thank for answer

**Comment by jbo-ads** [comment]
Which service, WMTS?

Where do you observe the compression, between source and cache?

**Comment by jratike80** [comment]
It is common to store compressed tiles. From  the documentation https://www.mapserver.org/mapcache/config.html

```
 <!-- format

       (Optional) format to use when storing a tile. This should be a format
       with high compression, e.g. PNG with compression "best", as the
       compression operation is only done once at tile creation time. If
       omitted, no recompression is applied to the image and mod-mapcache
       will store the exact image received from the <source>.

       Note that the <format> tag is mandatory if <metatile>, <metabuffer> or
       <watermark> are supplied, as in those cases recompression must be
       done.
   -->
   <format>PNG</format>```

**Comment by jezza12111** [comment]
Okay, i will describe my case and you will say me, where i made mistake, maybe :). I used MapCache 1.10 and WMS. I set format (PNG, compress best) and I made query to one tile, my folder with  tiles after this query had size 1.7MB, requested tile had 38kB. It seems look ok. Then I execute benchmark, I got 152 req/s. After those test I change my format commpresion to none, and send request again, my folder has the same size, requested tile has 60kB and benchmark got about 320req/s. It is a little weird, because I expected, that i got saved tiles, but mapcache recalculate the tile to bigger size. Second point is it, that where I use compression, I would expected bigger number of req/s, because the tile size is smaller, but It seems look like mapcache try compression again and then send me tiles. It is unnecessary CPU load, because I have stored compressed tile and mapcache try compression again, probably. Thank you for answer, it is a little complicated to describe.

**Comment by jratike80** [comment]
Please describe also your benchmark method. Do you make for example WMTS GetTile requests?

**Comment by jbo-ads** [comment]
With WMS, do you request maps with exact tile boundaries, of the size of exactly one tile?

MapCache is able to detect a tile request with WMS and delivers that tile without change. But if the requested map features more than one tile, MapCache uncompresses all needed tiles, assembles them, and then compresses the map picture, before delivery.

**Comment by jezza12111** [comment]
I used wrk or ab benchmark to one tile using WMS request, for example: wrk -t 1 -c20 -d10s "http://ip.of.server/mapcache?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=default&TILED=true&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=1624133.977013188%2C6379128.632546607%2C1780677.0109412288%2C6535671.666474649"
MapCache run as Apache Module, WMTS can try tomorrow.

**Comment by jezza12111** [comment]
Yes, now i understand, what mapcache do, thank you very much :)
