### ISSUE TITLE
SIGSEGV on disk cache

### ISSUE THREAD

**Issue by tomberek** [MapServer/mapcache#252]
Not sure if i'm doing something wrong, but disk based caching SIGSEGVs or spins for a while waiting for the lock in /tmp. All of this is local, none of this is NFS (previous similar issue mentioned that).

Switching to sqlite caching seems to work as expected.

```
sendto(6, "GET /mapserv?VERSION=1.1.1&REQUE"..., 301, MSG_NOSIGNAL, NULL, 0) = 301
poll([{fd=6, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
poll([{fd=6, events=POLLIN}, {fd=4, events=POLLIN}], 2, 199) = 1 ([{fd=6, revents=POLLIN}])
poll([{fd=6, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 1 ([{fd=6, revents=POLLIN|POLLRDNORM}])
recvfrom(6, "HTTP/1.1 200 OK\r\nServer: nginx/1"..., 16384, 0, NULL, NULL) = 540
close(6)                                = 0
close(4)                                = 0
close(5)                                = 0
mkdir("/home/tom/mapserver/cache/s/GoogleMapsCompatible/06/000/000/016/000/000", 0777) = -1 ENOENT (No such file or directory)
mkdir("/home/tom/mapserver/cache/s/GoogleMapsCompatible/06/000/000/016/000", 0777) = -1 ENOENT (No such file or directory)
mkdir("/home/tom/mapserver/cache/s/GoogleMapsCompatible/06/000/000/016", 0777) = -1 ENOENT (No such file or directory)
mkdir("/home/tom/mapserver/cache/s/GoogleMapsCompatible/06/000/000", 0777) = -1 ENOENT (No such file or directory)
mkdir("/home/tom/mapserver/cache/s/GoogleMapsCompatible/06/000", 0777) = -1 ENOENT (No such file or directory)
mkdir("/home/tom/mapserver/cache/s/GoogleMapsCompatible/06", 0777) = -1 ENOENT (No such file or directory)
mkdir("/home/tom/mapserver/cache/s/GoogleMapsCompatible", 0777) = -1 ENOENT (No such file or directory)
mkdir("/home/tom/mapserver/cache/s", 0777) = -1 ENOENT (No such file or directory)
mkdir("/home/tom/mapserver/cache", 0777) = 0
mkdir("/home/tom/mapserver/cache/s", 0777) = 0
mkdir("/home/tom/mapserver/cache/s/GoogleMapsCompatible", 0777) = 0
mkdir("/home/tom/mapserver/cache/s/GoogleMapsCompatible/06", 0777) = 0
mkdir("/home/tom/mapserver/cache/s/GoogleMapsCompatible/06/000", 0777) = 0
mkdir("/home/tom/mapserver/cache/s/GoogleMapsCompatible/06/000/000", 0777) = 0
mkdir("/home/tom/mapserver/cache/s/GoogleMapsCompatible/06/000/000/016", 0777) = 0
mkdir("/home/tom/mapserver/cache/s/GoogleMapsCompatible/06/000/000/016/000", 0777) = 0
mkdir("/home/tom/mapserver/cache/s/GoogleMapsCompatible/06/000/000/016/000/000", 0777) = 0
unlink("/home/tom/mapserver/cache/s/GoogleMapsCompatible/06/000/000/016/000/000/036.png") = -1 ENOENT (No such file or directory)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x30} ---
+++ killed by SIGSEGV (core dumped) +++
```

```
<mapcache>
    <source name="s" type="wms">
        <http>
            <url>http://127.0.0.1:8081/mapserv</url>
        </http>
        <getmap>
          <params>
             <LAYERS>s</LAYERS>
             <MAP>s.map</MAP>
          </params>
       </getmap>
    </source>
    <cache name="disk" type="disk">
        <base>/home/tom/mapserver/cache</base>
        <symlink_blank />
        <creation_retry>3</creation_retry>
    </cache>
    <cache name="sqlite" type="sqlite3">
     <dbfile>/tmp/{tileset}-{z}-{grid}.db</dbfile>
      <detect_blank/>
   </cache>
    <format name="PNG" type="PNG">
        <compression>fast</compression>
    </format>
    <tileset name="s">
        <source>s</source>
        <cache>disk</cache>
        <grid>GoogleMapsCompatible</grid>
    </tileset>
    <service type="wms" enabled="true">
        <format>PNG</format>
    </service>
    <service type="demo" enabled="true"/>
    <log_level>debug</log_level>
    <auto_reload>true</auto_reload>
</mapcache>
```

**Comment by tomberek** [comment]
looking at https://github.com/MapServer/mapcache/blob/main/lib/cache_disk.c#L537
```
    if(tile->tileset->format->type != GC_RAW && !tile->raw_image) {
```
I got the thought that it's possible that tileset has no format defined and the SIGSEGV is from that dereference.

Adding a `<format>PNG</format>` into the tileset config seems to fix the problem, but would also be good to add a check into L537. Docs declare this as optional.

**Comment by jbo-ads** [comment]
I finally got some time to work on this issue. It is so easy to reproduce that I wonder how it has been unnoticed until now.

Thank you for your analysis. I would add that the error is raised only with symlink_blank enabled.

My question is: what should MapCache do if no format is specified and symlink_blank is enabled?
- "No format" means that tiles are stored in the cache exactly as they are received from the source without decompression/recompression steps. Priority is given to speed.
- "symlink_blank" means that received tiles must be somehow analyzed to detect a uniform color, implying decompression/recompression. Priority is given to disk space.

At this point I think that MapCache should make `<format>` mandatory when `<symlink_blank>` is enabled. What are your thoughts @tomberek ?

**Comment by tomberek** [comment]
I was not aware that that's how symlink_blank worked. It makes sense (i've used "compressed file size" as a rudimentary blank tile checker in the past). 

1. Regardless there should be a null check
2. Add something to docs describing this (exactly your bullet points would be perfect
3. It seems formatting of some kind is required for the symlink_blank feature to work, thus the only other choice would be to have a default format, but that comes with it's own problems (or can be done later). For now it's reasonable to make `<format>` required when `<symlink_blank>` is present, because it describes the current behavior.

**Comment by jbo-ads** [comment]
Indeed, looking at the code just above, I see that `<detect_blank>` decodes the tile anyway. My first thought about speed vs. disk space may not be that relevant.

Therefore I now concur with your first view to add a NULL check without making `<format>` required when `<symlink_blank>` is present.

**Comment by tomberek** [comment]
My intention was actually to suggest all three items. But I’m relatively new to mapcache so you likely have a better idea what would be more intuitive in this case.
