### ISSUE TITLE
Add support for pcre2

### ISSUE THREAD

**Issue by sebastic** [MapServer/mapcache#272]
MapCache currently uses the deprecated [PCRE library](https://pcre.org/) (`pcre.h`), as used by the Debian package via libpcre3-dev.

The maintainer of the pcre3 package in Debian intends to remove it in favour of pcre2 (`pcre2.h`), because upstream is increasingly unwilling to fix issues in the old PCRE library, see: https://lists.debian.org/debian-devel/2021/11/msg00176.html

MapCache currently only supports the PCRE API, it should also support the PCRE2 API for regex support.

**Comment by jmckenna** [comment]
I recently hit this for the MS4W 5.0 release effort, but the bigger factor was that Apache HTTP was also not supporting pcre2, so in the end I fell back to PCRE 8.45 for the entire build.  Someday I agree, it would be great if Apache HTTP, MapCache and others support PCRE2.  (note that PHP8 does support PCRE2)

**Comment by sebastic** [comment]
pcre3 will be removed from Debian during the trixie development cycle, PCRE support in the mapcache package has been disabled to not have the mapcache package removed from the next stable release.
