### ISSUE TITLE
mapcache creates multible session for getting http sources and not a single one

### ISSUE THREAD

**Issue by a14stoner** [MapServer/mapcache#310]
I am seeding a map with a http source. 
Within one our mapcache creates around 720.000 sessions (one per request). 

Is it possible that mapcache requests the images within one session and not creates one session for every requested image?

**Comment by marisn** [comment]
This seems to be doable. I don't have time (and need) to implement it, thus just notes.

Download happens in http.c function `mapcache_http_do_request` and there is no session/connection/DNS reuse implemented. 
https://github.com/MapServer/mapcache/blob/main/lib/http.c#L102

Libcurl supports sharing of cookies, DNS, ssl and even connections. The documentation has nice examples:
https://everything.curl.dev/libcurl/sharing

One option would be to create three new functions: `http_setup`, `http_do_request` and `http_teardown`. This would allow to change separate places in code without a major rewrite of each `mapcache_http_do_request` callee. As for the seeder process – each worker thread could setup its own libcurl handle with shared properties and thus there would be no need for making a clever mutex-based locking. I don't know if there should be a cli flag to disable/enable such functionality.

**Comment by jratike80** [comment]
@a14stoner, please tell why did you close the ticket. I hope you have found a solution for your issue.

**Comment by marisn** [comment]
IMHO this should be reopened as it is a reasonable thing to implement. It could speed up seeding process a bit (although only testing could tell).

**Comment by a14stoner** [comment]
I simply dont need it anymore. If you want I'll reopen it. :)
