### ISSUE TITLE
Plan for 1.14.1 release

### ISSUE THREAD

**Issue by jmckenna** [MapServer/mapcache#319]
@jbo-ads, all : I propose a 1.14.1 release next week (mostly so packagers can include PCRE2 support, to go with the upcoming MapServer 8.2.0 release).   Any objections?  (see [changes](https://github.com/MapServer/mapcache/compare/rel-1-14-0...main))

**Comment by jbo-ads** [comment]
@jmckenna : no objection on my side. Actually I am glad to see that MapCache still arouses great interest.

**Comment by jmckenna** [comment]
1.14.1 release is now available
