### ISSUE TITLE
[Feature] Ability to specify immutable and public Cache-Control directives

### ISSUE THREAD

**Issue by marisn** [MapServer/mapcache#322]
At the moment it is possible only to specify tile max-age but it could be beneficial to be able to set `public` and `immutable` directives too. This should be configurable on a tileset level.

**Comment by jmckenna** [comment]
@marisn if you have any wishlist pull request coming, try to do them soon, as I'll try to cut the 1.14.1 release this coming Friday.

**Comment by marisn** [comment]
I do not have code for this yet. Just took a note to not forget about it.
