### ISSUE TITLE
MapServer config is missing

### ISSUE THREAD

**Issue by kontobaf** [MapServer/mapcache#332]
I installed MapServer on the Ubuntu server, after trying to attach a layer via VMS, I got the error msLoadConfig(): Unable to access file. See mapserver.org/mapfile/config.html for more information.
After looking at the documentation, I realized that the config file is not in the /usr/local/etc/ directory
What to do?

**Comment by jmckenna** [comment]
hi @kontobaf please use the MapServer-users list for getting MapCache help (this issue tracker is for reporting bugs etc).  Subscribe at https://lists.osgeo.org/mailman/listinfo/mapserver-users     thanks.
