### ISSUE TITLE
Having trouble building mapcache against nginx

### ISSUE THREAD

**Issue by MichaelMarkieta** [mapserver/mapcache#82]
I tried nginx-1.1.19 (from mapserver guide) and mapcache master and I realized that /mapcache/nginx/config doesn't exist, but config.in does. 

```
adding module in /usr/local/src/mapcache/nginx
./configure: error: no /usr/local/src/mapcache/nginx/config was found
```

Can someone explain why this is done this way? I have to change all instances of files with .in in order for ./configure to recognize the config file. Still fails after I change the file name.

```
make -f objs/Makefile
make[1]: Entering directory `/usr/local/src/nginx-1.1.19'
gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Wunused-function -Wunused-variable -Wunused-value -Werror -g  @APR_CPPFLAGS@ -I src/core -I src/event -I src/event/modules -I src/os/unix -I @PROJECT_BINARY_DIR@/include -I @APR_INCLUDE_DIR@ -I objs \
        -o objs/src/core/nginx.o \
        src/core/nginx.c
gcc: error: @APR_CPPFLAGS@: No such file or directory
make[1]: *** [objs/src/core/nginx.o] Error 1
make[1]: Leaving directory `/usr/local/src/nginx-1.1.19'
make: *** [build] Error 2
```

**Comment by AppreciateIT** [comment]
Hi guys, thanks for this thread, it got me over some stumbling-blocks for this building of mapserver and mapcache for nginx.  Now I'm at the final make for nginx, and I'm stuck as follows: 

/usr/local/src/nginx/nginx-1.10.2$ sudo make
...
...
objs/addon/nginx/ngx_http_mapcache_module.o \
objs/ngx_modules.o \
-ldl -lpthread -lcrypt -lmapcache /usr/lib/x86_64-linux-gnu/libapr-1.so /usr/lib/x86_64-linux-gnu/libaprutil-1.so -lpcre -lcrypto -lcryp
to -lz \
-Wl,-E
objs/addon/nginx/ngx_http_mapcache_module.o: In function `ngx_http_mapcache':
/usr/local/src/mapcache/nginx/ngx_http_mapcache_module.c:299: undefined reference to `mapcache_config_services_enabled'
collect2: error: ld returned 1 exit status
objs/Makefile:230: recipe for target 'objs/nginx' failed
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory '/usr/local/src/nginx/nginx-1.10.2'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

Any clues gentlemen?

Cheers,
Matt
